# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(default=b'ITEM NAME', max_length=25)),
                ('itemDescription', models.CharField(default=b'ITEM DESC', max_length=100)),
                ('itemRate', models.IntegerField(default=0)),
            ],
        ),
    ]
